
apiVersion: v1
kind: Service
metadata:
  name: logbook
  labels:
    app: logbook
    tier: backend
    team: mjdsoftware
spec:
  type: NodePort
  ports:
  - name: svcport
    port: 8080
    nodePort: 31623
    targetPort: 8080
  - name: debug
    port: 4000
    protocol: TCP
    targetPort: 4000
  selector:
    app: logbook
    tier: backend
