apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: translator-ingress
  annotations:
    nginx.ingress.kubernetes.io/affinity: "cookie"
spec:
  ingressClassName: nginx
  rules:
    - host: logbook
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: logbook
                port:
                  number: 8080