---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-self-control
  namespace: default
rules:
  - apiGroups: [ "" ]
    resources: [ "pods", "services"]
    verbs: [ "get", "list", "watch", "delete"]
  - apiGroups: [ "extensions" ]
    resources: [ "deployments" ]
    verbs: ["get", "list", "watch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: default-pod-self-control
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pod-self-control
subjects:
  - kind: ServiceAccount
    name: default
    namespace: default
